version: "3.9"

services:
  api:
    build: .
    container_name: sorora-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sorora
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    networks:
      - sorora-net

  mongodb:
    image: mongo:8.2
    container_name: sorora-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sorora-net

volumes:
  mongo_data:

networks:
  sorora-net:
    driver: bridge
